singleQuote: true
printWidth: 120
trailingComma: es5
tabWidth: 2
semi: true
arrowParen: 'avoid'
arrowParens: 'avoid'
plugins:
  - prettier-plugin-svelte
overrides:
  - files: '*.svelte'
    options:
      parser: svelte
